### ISSUE TITLE
MSB6006	"cmd.exe" exited with code 3 (build failure {visual studio 2019})

### ISSUE THREAD

**Issue by LethalManBoob** [lcferrum/qzdl#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"cmd.exe" exited with code 3.	qzdl	C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	220

**Comment by lcferrum** [comment]
Please provide more info. Do you have Qt 4.8 installed? Have you installed Qt add-in for VS?

**Comment by LethalManBoob** [comment]
I installed the latest q.t addon for vs 2019 https://marketplace.visualstudio.com/items?itemName=TheQtCompany.QtVisualStudioTools2019

**Comment by LethalManBoob** [comment]
i also installed the latest 5.2.3 qt in general and i cannot apply it in vs, it says it cant find the bin

**Comment by lcferrum** [comment]
ZDL uses Qt 4.8 and Qt 5 has some incompatibilities with previous Qt versions. You should install latest Qt 4.8 version (which is Qt 4.8.7) to be able to compile ZDL. Please refer to [COMPILE document](https://github.com/lcferrum/qzdl/blob/master/COMPILE) for compiling instructions.

**Comment by LethalManBoob** [comment]
Same error, the only versions i can find are for vs 2010 (incompatible). None for 2019.

**Comment by lcferrum** [comment]
As said in COMPILE, you have to compile Qt 4.8 from the sources in this case. Other options: install VS 2010 or try Qt 4.8 MinGW distribution w/ Qt Creator. In the latter case, you can, to some extent, use included Qt Creator project file (qzdl.pro). But there will be some compile errors (which you will be able to fix) and some features will be missing, because it's not intended to be used for Windows build.

Anyway, this is the wrong place to ask questions on how to install Qt for your particular build environment or compile Qt from the sources. I suggest you to ask on Stack Overflow or google it.

**Comment by LethalManBoob** [comment]
Okay so i followed everything on this site perfectly https://stackoverflow.com/questions/5601950/how-to-build-qt-for-visual-studio-2010

Still error code 3

No actual build instructions are in the compile folder, just requirements. Its a shame things couldnt be more simple or on more modern code.

**Comment by lcferrum** [comment]
Before trying to compile any 3rd-party code you should at least try to compile some basic stuff like ["Hello World"](https://doc.qt.io/archives/4.3/tutorial-t1.html) with your newly installed/compiled Qt to check that Qt toolchain really works. This "cmd.exe exited with error code 3" clearly indicates that something is wrong with your particular Qt installation. VS needs to launch qmake, which is external binary part of Qt, and it seems that it can't find it or passes wrong/incompatible command line params.

Original codebase was written for Qt 4.8. Aim of this fork is not in some abstract refactoring or migration to newer framework. The aim is keeping ZDL functionality up-to-date and adding new features needed by Doom community. So I left it as is, running on Qt 4.8. My idea is that instead of wasting your time on altering stuff to be compatible with your current tools, you just find the right tools for the job and get down to real business.

Qt 4.8.7 source code has makespecs only for VS 2003-2015. So I'm not even sure that you can really compile Qt 4.8 for VS 2019, at least without some modifications to Qt source code itself. Your best bet is to install VS 2010, because this is the latest VS version that Qt 4.8 distribution supports out of the box.

**Comment by LethalManBoob** [comment]
At this point its become too tedious for me to contuine. Thanks for your effort but it all is way too time consuming and stressful. I would love to see a version buildable with just visual studio needed but until then i will contuine to use your premade binarys. Thanks for your work regardless.
